### PR TITLE
5795 delete loan with step bug

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by emitche** [comment]
Basic Projects also have an error in similar cases. @arisah-ijeoma, can you add a test for BasicProjects as well as you did in the loan_flow_spec? Thank you!

**Comment by arisah-ijeoma** [comment]
will do @emitche

**Comment by arisah-ijeoma** [comment]
this has been addressed @emitche

**Comment by emitche** [comment]
Thanks for adding the Basic Projects test!

**Pull request merged**
