### PR TITLE
6881 fix story scope

### PR DESCRIPTION
**Pull request by arisah-ijeoma**
I need assistance with the specs

### CODE REVIEW

**Comment by emitche** [comment]
@hooverlunch, you would be best to help with fixing the tests.

**Comment by arisah-ijeoma** [comment]
I intended to write a feature spec but that didn't work out due to some js thingies

**Comment by emitche** [comment]
The attachments checkbox is nested inside loan type, but it should not be. The result is when the item validation shows, it shows in a weird place. image

**Comment by emitche** [comment]
Failed test is unrelated to this pull request.

**Pull request merged**
