### PR TITLE
8809 summernote for documentation

### PR DESCRIPTION
**Pull request by arisah-ijeoma**
The summernote spec is temporarily set to pending

### CODE REVIEW

**Comment by emitche** [comment]
From QA Review

## Bug: Modal button for add/edit link is white

### The problem
The modal button to add a link inside Summernote for this feature is white. The button displays like this when no content is added.
image

When hovering over the button, when no content has been added, the button looks like this:
image

When content is filled out, the button displays like this:
image

On hover, the button displays correctly, as a dark red button.

## The expected functionality
The button should look like the following when opening the form:
image

The button should look like this when the content is filled out on the form:
image

**Comment by emitche** [comment]
This looks good other than the above stated bug.

**Comment by emitche** [comment]
This has conflicts with develop that need to be resolved. This also has a bug.

**Comment by arisah-ijeoma** [comment]
screen shot 2018-09-03 at 12 39 36 pm
screen shot 2018-09-03 at 12 39 40 pm

This is what I have
What browser is being used to produce that bug?
I tried FF and it's fine

@emitche

**Comment by emitche** [comment]
Thanks!

**Comment by emitche** [comment]
I get this bug in Chrome and Firefox.

**Comment by emitche** [comment]
I'll see if I can get some more details or add a fix.

**Comment by emitche** [comment]
I moved the bug to Redmine 8848.

**Pull request merged**
