### PR TITLE
8324: Increase size of carousel indicators

### PR DESCRIPTION
**Pull request by emitche**
- Improve UX of public loans page carousel

### CODE REVIEW

**Comment by emitche** [comment]
@linesarefuzzy Does this visually look ok?

**Comment by emitche** [comment]
Fuzzy is likely to not be able to visually see these changes due to some Bootstrap issues with the TWW theme.

**Comment by emitche** [comment]
See #520.

**Comment by linesarefuzzy** [comment]
Looks good. Thanks!

**Pull request merged**
