### PR TITLE
6193 set log notification from header

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by linesarefuzzy** [comment]
Also please add a deployment issue to remind the deployer to test it on staging. Thanks!

**Comment by arisah-ijeoma** [comment]
I have updated the PR and also added the deployment story @linesarefuzzy

**Comment by emitche** [comment]
@linesarefuzzy @arisah-ijeoma How do you recommend testing this change in terms of confirming that the emails have the expected information?

**Comment by emitche** [comment]
I have what I need to test this. I paired with @linesarefuzzy.

**Pull request merged**
