### PR TITLE
7917 edit log in timeline and calendar

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by arisah-ijeoma** [comment]
this needs to be merged into #525 upon completion

The part of the story holding this is that the log doesn't automatically update when edited from timeline view
It requires a manual reload

**Comment by arisah-ijeoma** [comment]
It has the same issue as #464 

I'd suggest merging this into 7821 and applying a fix

**Comment by meltheadorable** [comment]
I'm not sure I understand the current status of this.

**Comment by emitche** [comment]
@meltheadorable 

This is ready for review. You can edit a log from the timeline and the loan calendar and both contexts update properly. There are some UI tweaks that have been moved to separate tickets for the next sprint.

However, since this has not been code reviewed yet, it may just make sense to bump this ticket to the next sprint to focus on other higher priority pull requests.

Thank you!

**Comment by meltheadorable** [comment]
Before I review this: has the delete PR that it's been branched off of been merged yet? I'd love to change the base to develop if we can.

**Comment by emitche** [comment]
No, #525 is still awaiting QA. This ticket can hold until next sprint.

**Comment by emitche** [comment]
QA: Works cleanly and as expected.

**Comment by emitche** [comment]
This test failure is to to a spec that needs tweaking and not related to this ticket.

**Pull request merged**
