### PR TITLE
6195 error on media upload

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by hooverlunch** [comment]
I believe there is a more standard way to fix this problem using Carrierwave:

https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays

I was assigned to pair on this issue but was never consulted for pairing so I'm not sure what happened there. @emitche @linesarefuzzy I think we will need to start over on this one and the work done to date on this will need to be discounted.

Too bad. @arisah-ijeoma I look forward to working with you to get this working nicely.

**Comment by arisah-ijeoma** [comment]
@hooverlunch, actually I started up this story on my own accord since I could recreate the bug
I also took a look at the link you posted. After some research, it turned out that that implementation didn't work with js redisplays.

I'm happy to look further into this and share ideas tho

**Comment by emitche** [comment]
@arisah-ijeoma and @linesarefuzzy: Could you two pair on this ticket? See my notes in Redmine. Thank you!

**Comment by emitche** [comment]
As I've not seen movement on this ticket, I am closing it. The branch should not be deleted.

**Comment by emitche** [comment]
@arisah-ijeoma Please update this branch with the most recent develop version. You can mark this as `needs-qa` afterwards.

I believee @meltheadorable already approved these changes.

**Comment by emitche** [comment]
image

This is the flow if an image is added and kind is not selected. If the user selects kind, but does not reattach the image, the image will disappear after trying to save and the user still needs to re-add the image.

**Comment by emitche** [comment]
@arisah-ijeoma: The user will still need to reattach their image, correct?

**Comment by arisah-ijeoma** [comment]
Yes @emitche

**Pull request merged**
