### PR TITLE
6132 add repayment to txn form; rename method

### PR DESCRIPTION
**Pull request by arisah-ijeoma**
This story is complete but is not ready to be merged to develop. This is because it concerns money matters and the backend is not done yet

### CODE REVIEW

**Comment by emitche** [comment]
Based on Redmine, this feature is ready to be reviewed. It has been marked on hold because there are some parts of the backend that are not yet implemented that are outside of the scope of this feature.

**Comment by hooverlunch** [comment]
There is not much here to review. What is here looks fine but I don't think this is the full feature? Going to wait on the full review then?

**Comment by emitche** [comment]
Please see my note in Redmine. Interest Calculator is not yet implemented. Those parts of Add Repayment do not need to be implemented in this feature, Add Repayment. This pull request is therefore code complete.

**Comment by emitche** [comment]
@hooverlunch This is code complete. Do you need to review this again?

**Comment by hooverlunch** [comment]
Yup fine with me.

**Comment by emitche** [comment]
Strange. This failed: 

````
  1) login should work

     Failure/Error: person = Person.find(params[:person_id])

     ActiveRecord::RecordNotFound:

       Couldn't find Person with 'id'=1

     # ./app/controllers/admin/calendar_events_controller.rb:14:in `index'

````

**Comment by hooverlunch** [comment]
@emitche Does it work if you run it locally? Could be a random failure.

**Comment by emitche** [comment]
@hooverlunch I'm not worried about this test failure, but wanted to point it out. Not related to the changes in this pull request.

**Pull request merged**
