### PR TITLE
7860 begin condensing with columns

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by emitche** [comment]
@arisah-ijeoma I can take care of the CSS tweaks and figuring out the right proportions.

**Comment by emitche** [comment]
This is good work so far. Thanks, @arisah-ijeoma.

**Comment by arisah-ijeoma** [comment]
thanks @emitche

**Comment by emitche** [comment]
This is both work from @arisah-ijeoma and me.

**Pull request merged**
