### PR TITLE
7647 remove html tag from yaml

### PR DESCRIPTION
**Pull request by arisah-ijeoma**

### CODE REVIEW

**Comment by arisah-ijeoma** [comment]
getting the undefined `qb_transaction_type` error

was `qb_transaction_type` changed to `qb_object_type` at some point?

**Comment by hooverlunch** [comment]
@arisah-ijeoma Yes it was. You can ignore this error for now.

**Comment by hooverlunch** [comment]
@arisah-ijeoma You should not please be tagging PRs that were marked as 'needs-minor-revision' as 'ready-for-review'. You can just mark them as 'complete' and 'needs-qa'. We should have this process written down somewhere if we don't already...

**Comment by emitche** [comment]
@arisah-ijeoma If your database is still having that error, please see https://redmine.sassafras.coop/issues/7684#note-9 for a fix.

**Comment by emitche** [comment]
@arisah-ijeoma 

This is good work. Both of these items appear in a context not inside a popup. So the rich text (links and bold) still works just fine. So I'll keep the formatting as it was originally, but I will use the renaming of the items. Thank you!

**Pull request merged**
